version: 2\nupdates:\n - package-ecosystem: "github-actions"\n   directory: "/"\n   schedule:\n     interval: "weekly"\n - package-ecosystem: "composer"\n   directory: "/"\n   schedule:\n     interval: "weekly"\n
